name: "GitHub build & release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Build"
        run: |
          python preset_build.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          draft: false
          files: |
            builds/mcwzh-meme.zip
            builds/mcwzh-meme_nomod_sfw.zip
            builds/mcwzh-meme_momod_noresource_sfw.zip
            builds/mcwzh-meme_compatible_sfw.zip
            builds/mcwzh-meme_compatible_nomod_sfw.zip
            builds/mcwzh-meme_compatible_nomod_noresource_sfw.zip
            builds/mcwzh-meme_legacy_noresource_sfw.zip