name: Check News

on:
  push:
    paths:
      - 'news.json'
      - 'alerts.json'
  pull_request:
    paths:
      - 'news.json'
      - 'alerts.json'

jobs:
  check-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: node check_news.js
      - name: Create comment
        uses: peter-evans/commit-comment@v1
        if: ${{ failure() }}
        with:
          body: |
            您的 `news.json` 或 `alerts.json` 格式出了些问题, 请及时修正
      - name: Push to global
        if: ${{ github.repository_owner == 'Teahouse-Studios' && github.ref == 'refs/heads/master' && success()}}
        run: curl -L purge.jsdelivr.net/gh/Teahouse-Studios/mcwzh-meme-resourcepack@master/news.json && curl -L purge.jsdelivr.net/gh/Teahouse-Studios/mcwzh-meme-resourcepack@master/alerts.json
