name: Test Build CI

on:
  push:
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yarn
        mkdir builds

    - name: Test build
      run: |
        node preset_build.js

    - name: Upload files built
      uses: actions/upload-artifact@v2
      with:
        name: files-built
        path: |
          builds
